version: 2
jobs:
  ruby2.7-rc:
    docker:
      - image: circleci/ruby:2.7-rc
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bin/test
  ruby2.6:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bin/test
  ruby2.5:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bin/test
workflows:
  version: 2
  build_and_test:
    jobs:
      - ruby2.7-rc
      - ruby2.6
      - ruby2.5